name: Deploy Python project to function app

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: shrinkifyapp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2

      - name: "Install libssl-dev"
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          override: true
          components: rustfmt, clippy

      - name: "Build binary"
        shell: bash
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl

      - name: "Copy binary"
        shell: bash
        run: |
          cp target/x86_64-unknown-linux-musl/release/handler .

      - name: "Run Azure Functions action"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
