name: Build and deploy to Azure Functions

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: shrinkifyapp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          override: true
          components: rustfmt, clippy

      - name: "Install musl-tools"
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools

      - name: "Build binary"
        shell: bash
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl

      - name: "Copy binary"
        shell: bash
        run: |
          cp target/x86_64-unknown-linux-musl/release/handler .

      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: handler
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Download"
        uses: actions/download-artifact@v2
        with:
          name: handler

      - name: "Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy"
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
